# Información del proyecto
sonar.projectKey=franco954_flask-API
sonar.organization=franco954

# Nombre y versión
sonar.projectName=flask-API Deploy
sonar.projectVersion=1.0

# Directorios de código fuente y tests
sonar.sources=app
sonar.tests=tests

# Lenguaje
sonar.language=py
sonar.python.version=3.11

# Reportes de cobertura
sonar.python.coverage.reportPaths=tests/coverage.xml

# Codificación
sonar.sourceEncoding=UTF-8

# Exclusiones (archivos que no se analizan)
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/env/**